services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

before_script:
  - sudo apt-get install shellcheck
  - make clean
  - make build

script:
  - shellcheck test/test.sh
  - sudo make test
