services:
  - docker

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - sudo apt-get install shellcheck
  - make clean
  - make build

script:
  - shellcheck test/test.sh
  - sudo make test
